---
format:
  html:
    page-layout: full
    toc: false

---

::: text-center
<h1>Publications</h1>

:::

### Submitted/Under review

#### Atmospheric Mechanisms of the Pattern Effect
*Under Review* at Journal of Geophysical Research Atmospheres\
<a href="https://essopenarchive.org/users/550217/articles/1349972-atmospheric-mechanisms-of-the-pattern-effect">Preprint</a> 

#### Is the high ECS in CESM2 degrading transient climate change projections over the 21st century?
*Under Review* at Journal of Advances in Modeling Earth Systems\
<a href="https://essopenarchive.org/users/550217/articles/1262413-is-the-high-ecs-in-cesm2-degrading-transient-climate-change-projections-over-the-21st-century">Preprint</a> 

### 2025

#### Decomposing Cloud Radiative Feedbacks By Cloud-Top Phase
Wall, C.J., D. Paynter, Y. Qin, M. Debolskiy, M. L. Duffy, T. Michibata, B. M. Duran, N. J. Lutsko, P-L Ma, B. Medeiros, T. Storelvmo, M.Zhao, 2025, Decomposing Cloud Radiative Feedbacks By Cloud-Top Phase, Journal of Climate, DOI: 10.1175/JCLI-D-24-0538.\
<a href="https://doi.org/10.1175/JCLI-D-24-0538.1">Link</a> 

#### Factors influencing underrepresented geoscientists’ decision to accept or decline a faculty job offer in the US
Duffy, M.L., L.Y. Barnes, C.D. Wirz, M.I. Ranganathan, M.A. Freilich, E.M. Freese, E. Lalk, J. Wilcots, 2025, Factors influencing underrepresented geoscientists’ decision to accept or decline a faculty job offer in the US, Nature Communications Earth and Environment, DOI: 10.1038/s43247-025-02052-3\
<a href="https://doi.org/10.1038/s43247-025-02052-3">Link</a> 

#### A new method for diagnosing effective radiative forcing from aerosol-cloud interactions in climate models
Duran, B.M., C.J. Wall, N.J. Lutsko, P.-L. Ma, Y. Qin, M.L. Duffy, B. Medeiros, T. Michibata, M. Debolski, 2025, A new method for diagnosing effective radiative forcing from aerosol-cloud interactions in climate models, Atmospheric Chemistry and Physics, DOI: 10.5194/acp-25-2123-2025\
<a href="https://doi.org/10.5194/acp-25-2123-2025">Link</a> 

### 2024

#### The interaction between climate forcing and feedbacks
Gettelman, A., T. Eidhammer, M.L. Duffy, D. McCoy, C. Song, D. Watson-Parris, 2024, The interaction between climate forcing and feedbacks, JGR Atmospheres, DOI: 10.1029/2024JD040857\
<a href="https://doi.org/10.1029/2024JD040857">Link</a> 

#### On the uncertainty of long-period return values of extreme daily precipitation
Wehner, M.F., M.L. Duffy, M. Risser, C.J. Paciorek, D.A. Stone, P. Pall, 2024, On the uncertainty of long-period return values of extreme daily precipitation, Frontiers in Climate. DOI: 10.3389/fclim.2024.1343072\
<a href="https://doi.org/10.3389/fclim.2024.1343072">Link</a> 

#### The Green’s function model intercomparison project (GFMIP) protocol
Bloch-Johnson, J., M.A.A. Rugenstein, M.J. Alessi, C. Proistosescu, M. Zhao, B. Zhang, A.I.L. Williams, J.M. Gregory, J. Cole, Y. Dong, M.L. Duffy, S.M. Kang, C. Zhou, The Green’s function model intercomparison project (GFMIP) protocol, 2024,  JAMES. DOI: 10.1029/2023MS003700\
<a href="https://doi.org/10.1029/2023MS003700">Link</a> 

#### Perturbing parameters to understand cloud contributions to climate change
Duffy, M.L., B. Medeiros, A.  Gettelman, T. Eidhammer, 2024, Perturbing parameters to understand cloud contributions to climate change, Journal of Climate. DOI: 10.1175/JCLI-D-23-0250.1\
<a href="https://doi.org/10.1175/JCLI-D-23-0250.1">Link</a> 

### 2023 and earlier

#### Intermodel spread in Walker circulation responses linked to spread in in moist stability and radiation responses
Duffy, M.L. and P.A. O’Gorman, 2023, Intermodel spread in Walker circulation responses linked to spread in in moist stability and radiation responses, JGR Atmospheres. DOI: 10.1029/2022JD037382\
<a href="https://doi.org/10.1029/2022JD037382">Link</a> 

#### Trends in the representation of women amongst US geoscience faculty from 1999 to 2020: The long road towards gender parity
Ranganathan, M.I., E. Lalk, E.M. Freese, M.A. Freilich, J. Wilcots, M.L. Duffy, R. Shivamoggi, 2021, Trends in the representation of women amongst US geoscience faculty from 1999 to 2020: The long road towards gender parity. AGU Advances. DOI: 10.1029/2021AV000436\
<a href="https://doi.org/10.1029/2021AV000436">Link</a> 

#### Worst climate outcomes are still possible
Duffy, P.B. and M.L. Duffy, 2021, Worst climate outcomes are still possible. Letter, Science, DOI: 10.1126/science.abg2720\
<a href="https://doi.org/10.1126/science.abg2720">Link</a> 

#### Importance of Laplacian of low-level warming for the response of precipitation to climate change over tropical oceans
Duffy, M.L., P.A. O’Gorman, L.E. Back, 2020, Importance of Laplacian of low-level warming for the response of precipitation to climate change over tropical oceans, Journal of Climate, DOI: 10.1175/JCLI-D-19-0365.1\
<a href="https://doi.org/10.1175/JCLI-D-19-0365.1">Link</a> 
